# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-03 16:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anggota',
            name='alamat',
        ),
        migrations.RemoveField(
            model_name='anggota',
            name='jenis_kelamin',
        ),
        migrations.RemoveField(
            model_name='anggota',
            name='masa_berlaku',
        ),
    ]
