# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-03 17:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0002_auto_20180903_1657'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Anggota',
        ),
    ]
